version: '3.9'

services:

  server:
    image: 'library-system-v1.jar'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=challenge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres